#pragma once

#define __SYSCALL_MEMORY_ALLOCATE 0x01
#define __SYSCALL_MEMORY_FREE 0x02
#define __SYSCALL_MEMORY_TRY_EXPAND 0x03

#define __SYSCALL_THREAD_CREATE 0x11
#define __SYSCALL_THREAD_EXIT 0x12
#define __SYSCALL_THREAD_DISPATCH 0x13
#define __SYSCALL_THREAD_JOIN 0x14
#define __SYSCALL_THREAD_DETACH 0x15
#define __SYSCALL_THREAD_GET_CURRENT 0x16

#define __SYSCALL_MUTEX_CREATE 0x21
#define __SYSCALL_MUTEX_LOCK 0x22
#define __SYSCALL_MUTEX_UNLOCK 0x23
#define __SYSCALL_MUTEX_DESTROY 0x24
#define __SYSCALL_MUTEX_TRY_LOCK 0x25

#define __SYSCALL_CONDITION_CREATE 0x31
#define __SYSCALL_CONDITION_WAIT 0x32
#define __SYSCALL_CONDITION_SIGNAL 0x33
#define __SYSCALL_CONDITION_SIGNAL_ALL 0x34
#define __SYSCALL_CONDITION_DESTROY 0x35

#define __SYSCALL_THREAD_STORAGE_CREATE 0x41
#define __SYSCALL_THREAD_STORAGE_DESTROY 0x42
#define __SYSCALL_THREAD_STORAGE_GET 0x43
#define __SYSCALL_THREAD_STORAGE_SET 0x44

#define __SYSCALL_SIGNAL_SET_HANDLER 0x51
#define __SYSCALL_SIGNAL_RAISE 0x52