#pragma once

#define EXCEPTION_INST_ADDR_MISALIGNED 0
#define EXCEPTION_INST_ACCESS_FAULT 1
#define EXCEPTION_ILLEGAL_INST 2

#define EXCEPTION_LOAD_ADDR_MISALIGNED 4
#define EXCEPTION_LOAD_ACCESS_FAULT 5
#define EXCEPTION_STORE_ADDR_MISALIGNED 6
#define EXCEPTION_STORE_ACCESS_FAULT 7

#define EXCEPTION_USER_ECALL 8
#define EXCEPTION_SUPERVISOR_ECALL 9

#define EXCEPTION_INTERRUPT (1U << 31)

#define TIMER_INTERRUPT 5
#define EXTERNAL_INTERRUPT 9