#pragma once

#define SYSCALL_MEM_ALLOC 0x01
#define SYSCALL_MEM_FREE 0x02

#define SYSCALL_THREAD_CREATE 0x11
#define SYSCALL_THREAD_EXIT 0x12
#define SYSCALL_THREAD_DISPATCH 0x13
#define SYSCALL_THREAD_JOIN 0x14

#define SYSCALL_MUTEX_CREATE 0x21
#define SYSCALL_MUTEX_LOCK 0x22
#define SYSCALL_MUTEX_UNLOCK 0x23
#define SYSCALL_MUTEX_DESTROY 0x24
#define SYSCALL_MUTEX_TRY_LOCK 0x25

#define SYSCALL_CONDITION_CREATE 0x31
#define SYSCALL_CONDITION_WAIT 0x32
#define SYSCALL_CONDITION_SIGNAL 0x33
#define SYSCALL_CONDITION_SIGNAL_ALL 0x34
#define SYSCALL_CONDITION_DESTROY 0x35

#define SYSCALL_TS_CREATE 0x41
#define SYSCALL_TS_DESTROY 0x42
#define SYSCALL_TS_GET 0x43
#define SYSCALL_TS_SET 0x44